name: ci

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.sh'
      - 'Vagrantfile'
jobs:
  run:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: latest
        id: v
      - name: Install build deps
        run: sudo apt-get install -y python3-dev
      - name: Set cflags
        run: echo CFLAGS="$(pkg-config python3 --cflags-only-I) -DPy_LIMITED_API=3" >> $GITHUB_ENV
      - name: Set ldflags
        run: echo LDFLAGS="$(pkg-config python3-embed --libs)" >> $GITHUB_ENV
      - name: Run tests
        run: v -cc gcc test py
